Bump Rspec version from 3.0 to 3.1 (#6)
When starting out on #5, running  `bundle exec rake spec` I ran into an error

    undefined method `include_chain_clauses_in_custom_matcher_descriptions=' for #<RSpec::Expectations::Configuration:0x00007fde1420e5a0> (NoMethodError)

That is because in `spec/spec_helper.rb` we use

    include_chain_clauses_in_custom_matcher_descriptions = true

which is introduced in rspec 3.1, but our local requirement ties Rspec to 3.0

After updating this rspec and rake, tests work fine locally.