Update truework.gemspec to rspec 3.1
Currently when running  `bundle exec rake spec` I run into an error

    undefined method `include_chain_clauses_in_custom_matcher_descriptions=' for #<RSpec::Expectations::Configuration:0x00007fde1420e5a0> (NoMethodError)

In spec/spec_helper.rb we use
    include_chain_clauses_in_custom_matcher_descriptions = true
which is introduced in rspec 3.1

After updating this rspec and rake